import {Dimensions, StyleSheet} from 'react-native';

const style = StyleSheet.create({
  mainContainer: {
    flex: 1,
    // paddingTop: Dimensions.get('screen').height / 2.2,
    backgroundColor: 'white',
  },
  curve: {
    borderRadius: 881,
    alignSelf: 'center',
    width: 800,
    height: Dimensions.get('screen').height,
  },
  imageLend: {
    height: 50,
    width: 50,
  },
  subView: {
    flexDirection: 'row',
    paddingTop: 60,
    alignSelf: 'center',
    width: Dimensions.get('window').width,
    justifyContent: 'space-evenly',
  },
  subView2: {
    flexDirection: 'row',
    paddingTop: 20,
    alignSelf: 'center',
    width: Dimensions.get('window').width,
    justifyContent: 'space-evenly',
  },
  subText: {
    color: 'white',
    lineHeight: 20,
    letterSpacing: 0.562,
    textTransform: 'uppercase',
    fontWeight: '400',
    fontFamily: 'Gotham Rounded',
    fontSize: 12,
  },
  renderView: {
    backgroundColor: 'white',
    paddingLeft: 10,
    borderRadius: 10,
    paddingTop: 5,
    flexDirection: 'row',
    paddingRight: 80,
    overflow: 'scroll',
    height: 130,
    marginBottom: 500,
  },
  triangle: {
    width: 80,
    height: 80,
    transform: [{rotate: '45deg'}],
    overflow: 'hidden',
    backgroundColor: 'red',
    borderRadius: 10,
  },
  renderView2: {
    width: '25%',
    paddingTop: 15,
  },
  renderView1: {
    width: '75%',
  },
  mainLogo: {
    width: 46,
    height: 46,
  },
  subView3: {
    flexDirection: 'row',
    paddingTop: Dimensions.get('screen').height / 25,
    alignSelf: 'center',
    width: Dimensions.get('window').width,
    justifyContent: 'space-evenly',
    paddingHorizontal: 10,
  },
  upgrade: {
    fontSize: 18,
    color: '#FF7A00',
    fontFamily: 'Gotham Rounded',
    fontWeight: '700',
    paddingLeft: 10,
  },
  description: {
    paddingHorizontal: 10,
    paddingTop: 5,
    paddingRight: 10,
    fontSize: 12,
    fontFamily: 'Proxima Nova',
    lineHeight: 17,
    fontWeight: '400',
    color: 'black',
    letterSpacing: 0.002,
  },
  women: {
    width: 185,
    height: 220,
    transform: [{scaleY: 1.3}],
    alignSelf: 'baseline',
  },
  safeArea: {
    flexDirection: 'row',
    backgroundColor: 'white',
    elevation: 10,
    shadowColor: 'rgb(26,26,26)',
    shadowOpacity: 0.1,
    shadowOffset: {height: 10, width: -5},
    shadowRadius: 5,
    justifyContent: 'space-evenly',
  },
  drawerLogo: {
    height: 20,
    width: 20,
  },
  drawerLogoView: {
    flexDirection: 'row',
    width: '20%',
    justifyContent: 'space-between',
  },
  mygt: {
    height: 50,
    width: 25,
    verticalAlign: 'top',
  },
  welcomeText: {
    color: '#FF8300',
    textAlign: 'center',
    alignSelf: 'center',
    fontSize: 18,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.656,
  },
  subDrawerView: {
    paddingTop: 10,
    paddingRight: 15,
    paddingLeft: 15,
  },
  welcomeView: {width: '60%', justifyContent: 'center'},
  question: {
    width: '20%',
    alignSelf: 'center',
  },
  help: {
    height: 40,
    width: 40,
    alignSelf: 'center',
  },
  middleOne: {
    flexDirection: 'row',
    paddingTop: 10,
    // paddingHorizontal: 10,
  },
  prepaidView: {
    width: '30%',
    paddingLeft: 7,
  },
  prepaidText: {
    fontSize: 14,
    fontWeight: '700',
    color: 'black',
  },
  coreView: {width: '27%', alignItems: 'center'},
  coreText: {
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 0.003,
    textAlign: 'center',
    color: 'black',
  },
  bundleView: {
    alignSelf: 'center',
    width: '43%',
    backgroundColor: '#F2F3F3',
    paddingVertical: 10,
    borderRadius: 40,
  },
  bundleText: {
    color: '#FF8300',
    textAlign: 'center',
    fontWeight: '600',
    textTransform: 'uppercase',
    fontSize: 12,
  },
  carouselView: {
    // height: Dimensions.get('window').height / 3,
    alignItems: 'center',
    marginBottom: 10,
  },
  renderItemOneView: {
    width: '100%',
    marginTop: 10,
    elevation: 20,
    marginBottom: 10,

    // height: Dimensions.get('window').height / 3.7,
    shadowOffset: {height: 1, width: 1},
    shadowColor: 'black',
    shadowOpacity: 0.5,
    shadowRadius: 4,
    backgroundColor: 'white',
    borderRadius: 10,
    paddingHorizontal: 30,
    zIndex: 1,
  },
  data: {
    color: '#004C9C',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.562,
    textAlign: 'center',
    paddingTop: 30,
  },
  gb: {
    textAlign: 'center',
    color: 'black',
    letterSpacing: 0.004,
    fontWeight: '700',
    fontSize: 38,
    paddingTop: 10,
  },
  gb1: {fontSize: 24},
  remain: {
    height: 10,
    width: Dimensions.get('window').width / 4,
    alignSelf: 'center',
  },
  remainText: {
    textAlign: 'center',
    color: '#5B5B5B',
    paddingBottom: 15,
  },
  ends: {
    color: '#58595B',
    fontFamily: 'Gotham Rounded',
    textAlign: 'center',
    paddingTop: 20,
    paddingBottom: 10,
  },
  buyView: {
    backgroundColor: '#F2F3F3',
    borderRadius: 10,
    marginBottom: 5,
  },
  buy: {
    color: '#FF8300',
    textAlign: 'center',
  },
});

export default style;
